// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_3ay6m6m1OVnFxkuGGOY3j3hJzHTwoB0',
    appId: '1:680343359971:web:52226e45e368836d7d90d6',
    messagingSenderId: '680343359971',
    projectId: 'flutter-chat-app-171c0',
    authDomain: 'flutter-chat-app-171c0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-171c0.appspot.com',
    measurementId: 'G-NXF6EC87YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPcOicC9U5hFyhFyOv8fyspz2U1EZaWYM',
    appId: '1:680343359971:android:f0ef9575e3d412a57d90d6',
    messagingSenderId: '680343359971',
    projectId: 'flutter-chat-app-171c0',
    storageBucket: 'flutter-chat-app-171c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5WKuJJueQGjwPEB_Ro-ACMUb1f6Bb4Ug',
    appId: '1:680343359971:ios:8d18d2553c75b1d17d90d6',
    messagingSenderId: '680343359971',
    projectId: 'flutter-chat-app-171c0',
    storageBucket: 'flutter-chat-app-171c0.appspot.com',
    iosBundleId: 'com.example.chatIfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5WKuJJueQGjwPEB_Ro-ACMUb1f6Bb4Ug',
    appId: '1:680343359971:ios:8d18d2553c75b1d17d90d6',
    messagingSenderId: '680343359971',
    projectId: 'flutter-chat-app-171c0',
    storageBucket: 'flutter-chat-app-171c0.appspot.com',
    iosBundleId: 'com.example.chatIfy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_3ay6m6m1OVnFxkuGGOY3j3hJzHTwoB0',
    appId: '1:680343359971:web:8630963ecef08e147d90d6',
    messagingSenderId: '680343359971',
    projectId: 'flutter-chat-app-171c0',
    authDomain: 'flutter-chat-app-171c0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-171c0.appspot.com',
    measurementId: 'G-KD5K6H0GP9',
  );
}